apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi-d
  labels:
    app: pokeapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokeapi
  template:
    metadata:
      labels:
        app: pokeapi
    spec:
      containers:
      - name: pokeapi
        image: deyvid14/pokeapi:v2
        ports:
          - containerPort: 80
        envFrom:
        - configMapRef:
            name: pokeapi-env