apiVersion: v1
kind: Service
metadata:
  name: pokeapi-lb
spec:
  selector:
    app: pokeapi
  # ports:
  # - port: 80
  #   targetPort: 80
  type: LoadBalancer
  ports:
  - name: httport
    port: 85
    targetPort: 80
    nodePort: 31416