apiVersion: v1
kind: Service
metadata:
  name: pokeapi-lb
spec:
  selector:
    app: pokeapi
  type: LoadBalancer
  ports:
  - name: http-port
    protocol: TCP
    port: 85  # Puerto expuesto en el servicio
    targetPort: 80  # Puerto expuesto en el contenedor
    nodePort: 31416  # Para acceder desde el exterior (en el rango 30000-32767)
# spec:
#   selector:
#     app: pokeapi
#   # ports:
#   # - port: 85
#   #   targetPort: 80
#   type: LoadBalancer
